### ISSUE TITLE
When trying to install requirements.txt:

### ISSUE THREAD

**Issue by FemBoxbrawl** [AIFSH/ComfyUI-XTTS#7]
Collecting docopt
  Using cached docopt-0.6.2.tar.gz (25 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\leeco\AppData\Local\Temp\pip-install-at892h0_\docopt_eee0636ad1a04951a8485b61b5f3efdb\setup.py", line 3, in <module>
          from docopt import __version__
      ModuleNotFoundError: No module named 'docopt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by Bastrijdesign** [comment]
having the same issue did you manage to fix?

**Comment by Mozoloa** [comment]
https://github.com/fredconex/ComfyUI-SongBloom/issues/1#issuecomment-3020070941 try something like that
